In [21]:
import json
import pandas as pd
from IPython.display import Image, JSON, display
from run_main import run

The strucure of an evolved model can be examined because all the parameters are stored in a readable JSON format configuration file. First, set the folder that contains the JSON file:

In [26]:
outputFolderName="notebooks/example_W2D18L"

Load the JSON file. Every time a simulation or evoltution is performed the new evolved parameters and worm states are rewritten to the JSON file, which will therefore need to be reloaded:

In [27]:
with open(outputFolderName + '/worm_data_worm.json') as json_file:
    json_data = json.load(json_file)

The full expandable JSON can be examined.

In [28]:
JSON(filename=outputFolderName + '/worm_data_worm.json')

The "nervous_system" field contains several sub-fields.

In [13]:
pd.DataFrame({"nervous_system keys": json_data["nervous_system"].keys()})

    nervous_system keys
0            cell_names
1  cell_names_no_suffix
2                 cells
3        chemical_conns
4      electrical_conns
5            model_name

The "cell_names" field contains the list of nervous system cells.

In [7]:
print(json_data['nervous_system']['cell_names']['value'])

['DB_0', 'DD_0', 'VBA_0', 'VDA_0', 'VBP_0', 'VDP_0', 'DB_1', 'DD_1', 'VBA_1', 'VDA_1', 'VBP_1', 'VDP_1', 'DB_2', 'DD_2', 'VBA_2', 'VDA_2', 'VBP_2', 'VDP_2', 'DB_3', 'DD_3', 'VBA_3', 'VDA_3', 'VBP_3', 'VDP_3', 'DB_4', 'DD_4', 'VBA_4', 'VDA_4', 'VBP_4', 'VDP_4', 'DB_5', 'DD_5', 'VBA_5', 'VDA_5', 'VBP_5', 'VDP_5', 'SMDD_0', 'RMDD_0', 'SMDV_0', 'RMDV_0']

The "chemical_conns" and "electrical_conns" fields contain the list of connections between nervous system cells.

In [8]:
print(json_data['nervous_system']['chemical_conns']['value'])

[{'from': 'DB_0', 'to': 'DB_0', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'DD_0', 'to': 'DD_0', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'DB_0', 'to': 'DD_0', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'VBA_0', 'to': 'DD_0', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBP_0', 'to': 'DD_0', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBA_0', 'to': 'VBA_0', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDA_0', 'to': 'VDA_0', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBA_0', 'to': 'VDA_0', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_0', 'to': 'VDA_0', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DD_0', 'to': 'VDA_0', 'weight': {'evotag': 9, 'value': 15.0}}, {'from': 'VBP_0', 'to': 'VBP_0', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDP_0', 'to': 'VDP_0', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBP_0', 'to': 'VDP_0', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_0', 'to': 'VDP_0', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DB_1', 'to': 'DB_1', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'DD_1', 'to': 'DD_1', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'DB_1', 'to': 'DD_1', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'VBA_1', 'to': 'DD_1', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBP_1', 'to': 'DD_1', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBA_1', 'to': 'VBA_1', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDA_1', 'to': 'VDA_1', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBA_1', 'to': 'VDA_1', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_1', 'to': 'VDA_1', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DD_1', 'to': 'VDA_1', 'weight': {'evotag': 9, 'value': 15.0}}, {'from': 'VBP_1', 'to': 'VBP_1', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDP_1', 'to': 'VDP_1', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBP_1', 'to': 'VDP_1', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_1', 'to': 'VDP_1', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DB_2', 'to': 'DB_2', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'DD_2', 'to': 'DD_2', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'DB_2', 'to': 'DD_2', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'VBA_2', 'to': 'DD_2', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBP_2', 'to': 'DD_2', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBA_2', 'to': 'VBA_2', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDA_2', 'to': 'VDA_2', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBA_2', 'to': 'VDA_2', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_2', 'to': 'VDA_2', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DD_2', 'to': 'VDA_2', 'weight': {'evotag': 9, 'value': 15.0}}, {'from': 'VBP_2', 'to': 'VBP_2', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDP_2', 'to': 'VDP_2', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBP_2', 'to': 'VDP_2', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_2', 'to': 'VDP_2', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DB_3', 'to': 'DB_3', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'DD_3', 'to': 'DD_3', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'DB_3', 'to': 'DD_3', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'VBA_3', 'to': 'DD_3', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBP_3', 'to': 'DD_3', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBA_3', 'to': 'VBA_3', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDA_3', 'to': 'VDA_3', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBA_3', 'to': 'VDA_3', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_3', 'to': 'VDA_3', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DD_3', 'to': 'VDA_3', 'weight': {'evotag': 9, 'value': 15.0}}, {'from': 'VBP_3', 'to': 'VBP_3', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDP_3', 'to': 'VDP_3', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBP_3', 'to': 'VDP_3', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_3', 'to': 'VDP_3', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DB_4', 'to': 'DB_4', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'DD_4', 'to': 'DD_4', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'DB_4', 'to': 'DD_4', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'VBA_4', 'to': 'DD_4', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBP_4', 'to': 'DD_4', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBA_4', 'to': 'VBA_4', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDA_4', 'to': 'VDA_4', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBA_4', 'to': 'VDA_4', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_4', 'to': 'VDA_4', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DD_4', 'to': 'VDA_4', 'weight': {'evotag': 9, 'value': 15.0}}, {'from': 'VBP_4', 'to': 'VBP_4', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDP_4', 'to': 'VDP_4', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBP_4', 'to': 'VDP_4', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_4', 'to': 'VDP_4', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DB_5', 'to': 'DB_5', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'DD_5', 'to': 'DD_5', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'DB_5', 'to': 'DD_5', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'VBA_5', 'to': 'DD_5', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBP_5', 'to': 'DD_5', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 4.7314342549040935}}, {'from': 'VBA_5', 'to': 'VBA_5', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDA_5', 'to': 'VDA_5', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBA_5', 'to': 'VDA_5', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_5', 'to': 'VDA_5', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'DD_5', 'to': 'VDA_5', 'weight': {'evotag': 9, 'value': 15.0}}, {'from': 'VBP_5', 'to': 'VBP_5', 'weight': {'evotag': 5, 'value': -6.913324601427629}}, {'from': 'VDP_5', 'to': 'VDP_5', 'weight': {'evotag': 6, 'value': -0.5206259813978599}}, {'from': 'VBP_5', 'to': 'VDP_5', 'weight': {'evotag': 7, 'value': 0.20082856347574748}}, {'from': 'DB_5', 'to': 'VDP_5', 'weight': {'evotag': 8, 'value': 9.462868509808187}}, {'from': 'SMDD_0', 'to': 'SMDD_0', 'weight': {'evotag': 21, 'value': -12.205910238422963}}, {'from': 'SMDV_0', 'to': 'SMDD_0', 'weight': {'evotag': 23, 'value': 1.1019453603844702}}, {'from': 'RMDD_0', 'to': 'RMDD_0', 'weight': {'evotag': 22, 'value': 5.7813912643060945}}, {'from': 'SMDV_0', 'to': 'RMDD_0', 'weight': {'evotag': 24, 'value': 15.0}}, {'from': 'RMDV_0', 'to': 'RMDD_0', 'weight': {'evotag': 25, 'value': -15.0}}, {'from': 'SMDV_0', 'to': 'SMDV_0', 'weight': {'evotag': 21, 'value': -12.205910238422963}}, {'from': 'SMDD_0', 'to': 'SMDV_0', 'weight': {'evotag': 23, 'value': 1.1019453603844702}}, {'from': 'RMDV_0', 'to': 'RMDV_0', 'weight': {'evotag': 22, 'value': 5.7813912643060945}}, {'from': 'SMDD_0', 'to': 'RMDV_0', 'weight': {'evotag': 24, 'value': 15.0}}, {'from': 'RMDD_0', 'to': 'RMDV_0', 'weight': {'evotag': 25, 'value': -15.0}}]

Connections contain the "from" and "to" cells and the "weight" value. This particular connection also contains the "evotag" field which means its value is not fixed, but is to be optimized if the evolutionary algorithm is executed (see below.)

In [54]:
print(json_data['nervous_system']['chemical_conns']['value'][3])

{'from': 'DD_0', 'to': 'DB_0', 'weight': {'evotag': 12, 'value': -5.824601051221684}}

The "nervous_system", "cells" field contains the parameters specific to the particular cell. The cell model used here has 'bias', 'gain' and 'tau' parameters. The last value of the dynamical 'state' is also included. The "cell_class" is mainly used for plotting. The 'bias' parameter also includes the 'evotag' field meaning it is not fixed if an optimization is performed (see below.)

In [72]:
print(json.dumps(json_data['nervous_system']['cells']['DB_0'], indent=2))

{
  "bias": {
    "evotag": 4,
    "value": 9.35093819108163
  },
  "cell_class": {
    "value": "vnc"
  },
  "gain": {
    "value": 1.0
  },
  "state": {
    "value": -10.68120539862163
  },
  "tau": {
    "value": 1
  }
}

In [64]:
print(json.dumps(json_data['nervous_system']['cells']['VD_1'], indent=2))

{
  "bias": {
    "evotag": 5,
    "value": 12.195762348100372
  },
  "cell_class": {
    "value": "vnc"
  },
  "gain": {
    "value": 1.0
  },
  "state": {
    "value": -12.078596445696128
  },
  "tau": {
    "value": 1.0
  }
}

The JSON configuration file contains all the worm parameters. For example, the stretch receptors contain the weights to and from body segments and to and from the nervous sytem:

In [15]:
pd.DataFrame({"stretch receptor keys": json_data["stretch_receptor"].keys()})

   stretch receptor keys
0              d_weights
1                 n_segs
2              n_stretch
3           ns_d_weights
4           ns_v_weights
5              plot_size
6           sr_head_gain
7             sr_head_sr
8            sr_vnc_gain
9              sr_vnc_sr
10                  type
11             v_weights

Weights from body segments to dorsal stretch receptors:

In [18]:
print(json.dumps(json_data['stretch_receptor']['d_weights']))

{"message": "Weights from body segments to ventral SR", "value": [{"from_seg": 7, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 8, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 9, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 10, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 11, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 12, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 13, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 14, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 15, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 16, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 17, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 18, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 19, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 20, "to_sr": 1, "weight": {"value": -9.149246494997389}}, {"from_seg": 7, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 8, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 9, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 10, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 11, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 12, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 13, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 14, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 15, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 16, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 17, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 18, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 19, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 20, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 21, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 22, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 23, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 24, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 25, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 26, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 27, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 28, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 29, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 30, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 31, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 32, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 33, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 34, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 35, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 36, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 37, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 38, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 39, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 40, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 41, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 42, "to_sr": 7, "weight": {"value": -26.683438106385438}}]}

Weights from dorsal stretch receptors to Nervous System:

In [19]:
print(json.dumps(json_data['stretch_receptor']['ns_d_weights']))

{"message": "Weights from dorsal SR to Nervous System", "value": [{"from_sr": 2, "to_ns": "DB_0", "weight": {"value": 1.0}}, {"from_sr": 3, "to_ns": "DB_1", "weight": {"value": 1.0}}, {"from_sr": 4, "to_ns": "DB_2", "weight": {"value": 1.0}}, {"from_sr": 5, "to_ns": "DB_3", "weight": {"value": 1.0}}, {"from_sr": 6, "to_ns": "DB_4", "weight": {"value": 1.0}}, {"from_sr": 7, "to_ns": "DB_5", "weight": {"value": 1.0}}, {"from_sr": 1, "to_ns": "SMDD_0", "weight": {"value": 1.0}}]}

Change a particular particular parameter. (Note: if the parameter changed is one that is set to be 'optimizable' so that it has an 'evotag' parameter next to the value field, then any change made here will have no effect if a further optimization is performed) :

In [24]:
args = dict(
    simduration=30, #duration of simulation run
    simtransient=0, #transient of simulation run
    modelFolder="Worm2D", #folder containing the compiled C++ binary code
    modelName="W2DSR",
    inputFolderName=outputFolderName, #output folder
    outputFolderName=outputFolderName + "_modified",
    overwrite=True, #allow overwrite of output folder 
    randInitState=False, #use fixed initial conditions
    doTestRun=True, #run a single simple simulation
)

In [25]:
args['doEvol'] = False 
args['modelName'] ="W2DSR" #rerun using the generic json loaded model
run(**args) #the ExampleActivity.png and Motion.png figures must be reloaded above to see results

Directory 'notebooks/example_W2D18L_modified' already exists and the simulation results will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '66', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '30', '-st', '0', '--doevol', '0', '-cpt', '0', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '1', '--evoType', 'Evo21']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json

Error:
main_osc: Worm2D.h:830: virtual void Worm2D::setMuscleInputOrig(): Assertion `0 && "setMuscleInputOrig needs overriding"' failed.

SystemExit: -6

In [45]:
json_data['nervous_system']['cells']['VD_1']['bias']['value'] = 3
json_data['nervous_system']['chemical_conns']['value'][3]['weight']['value']=-3
json_data['stretch_receptor']['sr_a_gain']['value']=30

The json file needs to be re-saved before simulations are performed.

In [70]:
json_data['nervous_system']['cells']['DB_0']['tau']['value'] = 1

In [71]:
with open(outputFolderName + '/worm_data_worm.json', "w") as f:
    json.dump(json_data, f)